In [2]:
import numpy as np


In [3]:
#Task 1
print("----Task 1-----")
array1 = np.array([1,2,3])
print(array1)


----Task 1-----
[1 2 3]


In [4]:
#Task 2
print("----Task 2-----")
array2 = array1.astype(float)
print(array2)


----Task 2-----
[1. 2. 3.]


In [5]:
#Task 3
print("----Task 3-----")
array3 = np.arange(0,10)
print(array3)


----Task 3-----
[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Task 4
print("----Task 4-----")
array4 = np.linspace(0,23,7)
print(array4)

----Task 4-----
[ 0.          3.83333333  7.66666667 11.5        15.33333333 19.16666667
 23.        ]


In [11]:
#Task 5
print("----Task 5-----")
array5 = np.full((2,5,1,5,2,1),5)
print(array5.shape)
print(array5)

----Task 5-----
(2, 5, 1, 5, 2, 1)
[[[[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]]




 [[[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5

In [12]:
#Task 6
print("----Task 6-----")
array6 = np.squeeze(array5)
print(array6.shape)


----Task 6-----
(2, 5, 5, 2)


In [13]:
#Task 7
print("----Task 7-----")
array7 = np.reshape(array6,(20,5))
print(array7.shape)


----Task 7-----
(20, 5)


In [14]:
#Task 8
print("----Task 8-----")
mean = 21
sigma = 4.5
array8 = np.random.normal(mean,sigma, (3,3,12,3))
print ("max: " ,np.max(array8))
print ("mean: " ,np.mean(array8))
print ("std: " ,np.std(array8))
print ("var: " ,np.var(array8))
print ("min: " ,np.min(array8))


----Task 8-----
max:  33.324043556739014
mean:  20.764888669394654
std:  4.3640185551898405
var:  19.044657950041223
min:  9.712221315691753


In [15]:
#Task 10
print("----Task 10-----")
array10 = array3.flatten()
print(array10)

----Task 10-----
[0 1 2 3 4 5 6 7 8 9]
