# Text Classification Using Bernoulli Naive Bayes algorithm

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df.shape

(5572, 2)

In [3]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
pip install nltk

^C
Note: you may need to restart the kernel to use updated packages.


# Text Cleaning -
### Remove Punctuation, remove stop words, tokenize the setence into words, convert words into numbers

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\usman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [12]:
from nltk.corpus import stopwords

stopWords = set(stopwords.words('english'))
print(stopWords)


{'themselves', 'or', 'about', 'been', 'hers', 'don', 'isn', 'no', "you're", 't', "you'll", "wouldn't", 'we', 'yourself', 'whom', 'they', 'in', 'few', 'but', 'these', 'too', 'doesn', 'than', 'there', 'by', 'am', 've', 'against', "doesn't", 'wasn', 'nor', 'me', 'further', 'haven', 'y', 'do', 'who', 'didn', 'o', 'he', 'couldn', 'itself', 'their', 'will', 'some', 'myself', "mightn't", 'only', 'the', 'aren', "shouldn't", "you've", 'his', 'here', 'because', 'being', 'yours', 'below', 'and', 'was', 's', 'weren', 'hadn', 'more', 'herself', 'were', 'its', 'on', "wasn't", 'up', 'be', 'are', 'should', 'as', 'before', 'you', 'it', 'doing', 'she', 'at', 'why', 'same', 'ma', 'himself', 'again', 'mightn', 'down', 'is', 'ours', 'd', "isn't", 'now', 'hasn', 'this', 'him', 'each', 'needn', "should've", 'between', 'm', 'has', 'other', 'very', 'theirs', 'after', 're', 'can', 'did', 'won', 'mustn', 'yourselves', "won't", 'those', 'under', "shan't", 'ourselves', "mustn't", 'what', 'so', 'had', 'until', "she

In [13]:
import string
def text_cleaning(a):
 cleaning = [char for char in a if char not in string.punctuation]
 #print(cleaning)
 cleaning=''.join(cleaning)
 #print(cleaning)   
 return [word for word in cleaning.split() if word.lower() not in stopwords.words('english')]



In [16]:

from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_cleaning).fit(df['Message']) 
  

In [18]:
title_bow = bow_transformer.transform(df['Message'])

print(title_bow)

  (0, 1107)	1
  (0, 1480)	1
  (0, 2058)	1
  (0, 4651)	1
  (0, 5214)	1
  (0, 5215)	1
  (0, 5766)	1
  (0, 6214)	1
  (0, 6903)	1
  (0, 6934)	1
  (0, 7552)	1
  (0, 7665)	1
  (0, 8333)	1
  (0, 8914)	1
  (0, 10962)	1
  (0, 11160)	1
  (1, 2449)	1
  (1, 3062)	1
  (1, 7698)	1
  (1, 8587)	1
  (1, 10695)	1
  (1, 11069)	1
  (2, 73)	1
  (2, 421)	1
  (2, 428)	1
  :	:
  (5568, 6688)	1
  (5568, 6879)	1
  (5568, 7156)	1
  (5568, 11415)	1
  (5569, 3226)	1
  (5569, 3719)	1
  (5569, 8249)	1
  (5569, 10196)	1
  (5570, 4506)	1
  (5570, 5052)	1
  (5570, 5248)	1
  (5570, 6279)	1
  (5570, 6696)	1
  (5570, 6796)	1
  (5570, 6981)	1
  (5570, 7284)	1
  (5570, 7391)	1
  (5570, 7797)	1
  (5570, 8417)	1
  (5570, 9912)	1
  (5570, 10784)	1
  (5570, 11003)	1
  (5571, 3429)	1
  (5571, 8345)	1
  (5571, 10645)	1


In [19]:
X = title_bow.toarray()
print(X)

 
X.shape  # 1000,2159  # 2159 seperate words in our dataset and 1000 rows

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(5572, 11422)

In [21]:
# If you want you can store it in a dataframe also
dd=pd.DataFrame(data=title_bow.toarray())
dd

0      1      2      3      4      5      6      7      8      9      \
0         0      0      0      0      0      0      0      0      0      0   
1         0      0      0      0      0      0      0      0      0      0   
2         0      0      0      0      0      0      0      0      0      0   
3         0      0      0      0      0      0      0      0      0      0   
4         0      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5567      0      0      0      0      0      0      0      0      0      0   
5568      0      0      0      0      0      0      0      0      0      0   
5569      0      0      0      0      0      0      0      0      0      0   
5570      0      0      0      0      0      0      0      0      0      0   
5571      0      0      0      0      0      0      0      0      0      0   

      ...  11412  11413  11414  11415  11416  11417  11418  11419  11420  \
0     ...      0      0      0      0      0      0      0      0      0   
1     ...      0      0      0      0      0      0      0      0      0   
2     ...      0      0      0      0      0      0      0      0      0   
3     ...      0      0      0      0      0      0      0      0      0   
4     ...      0      0      0      0      0      0      0      0      0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5567  ...      0      0      0      0      0      0      0      0      0   
5568  ...      0      0      0      1      0      0      0      0      0   
5569  ...      0      0      0      0      0      0      0      0      0   
5570  ...      0      0      0      0      0      0      0      0      0   
5571  ...      0      0      0      0      0      0      0      0      0   

      11421  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
5567      0  
5568      0  
5569      0  
5570      0  
5571      0  

[5572 rows x 11422 columns]

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, df.Category,test_size=0.2, random_state=50)

In [24]:
#from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB().fit(x_train,y_train)

In [25]:
prediction = model.predict(x_test)
print(prediction)

['spam' 'ham' 'ham' ... 'ham' 'ham' 'spam']


In [26]:
from sklearn.metrics import accuracy_score

accuracy_score(prediction,y_test)

0.9668161434977578

In [27]:
y_test  #actual records of y_test

3409    spam
2103     ham
2665     ham
3239     ham
1205    spam
        ... 
5020     ham
2141     ham
1265     ham
4094     ham
1839    spam
Name: Category, Length: 1115, dtype: object